import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { Customer } from '../model/customer';
import { CUSTOMER_REGION } from '../constants';
@Injectable({
  providedIn: 'root',
})
export class CustomerService {

  private customers: Customer[] = this.getCustomers();
  private newCustomers: Customer[] = this.getNewCustomers();

   getBusinessHubs(regionName: string): string[] {
    const region = CUSTOMER_REGION.find(region => region.name === regionName);
    return region ? region.businessHubs.map(hub => hub.name) : [];
  }
  
  // Function to get service centres for a selected business hub as an array of strings
   getServiceCentres(regionName: string, businessHubName: string): string[] {
    const region = CUSTOMER_REGION.find(region => region.name === regionName);
    if (region) {
      const businessHub = region.businessHubs.find(hub => hub.name === businessHubName);
      return businessHub ? businessHub.serviceCentres.map(sc => sc.name) : [];
    }
    return [];
  }
  
  getCustomers(): Customer[] {
    return [
      {
        id: 1001,
        customerFullName: 'John Doe',
        accountNo: 'ACC001',
        meterNo: 'MTR001',
        address: '123 Elm St',
        city: 'Springfield',
        lga: 'LGA1',
        state: 'State1',
        nearestLandmark: 'Near the park',
        date: new Date('2024-09-27'),
        latitude: '12.345678',
        longitude: '98.765432',
        customerId: 'CUST001',
        cin: 'CIN001',
        applicationDate: '2024-01-15',
        mobile: '1234567890',
        email: 'johndoe@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R1',
        correctTariffCode: 'R1',
        tariffClass: 'LFN',
        feeder: 'Feeder1',
        feederId: 'FEED001',
        serviceCenter: 'Center1',
        distributionName: 'Distribution1',
        dssId: 'DSS001',
        ltPoleId: 'LT001',
        serviceWire: 'Wire1',
        upriser: 'Upriser1',
        region: 'Region1',
        businessHub: 'Hub1',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Business',
        customerNIN: 'NIN001',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1000',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Electronics',
        customerMeterManufacturer: 'Manufacturer1',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'John Doe',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1002,
        customerFullName: 'Jane Smith',
        accountNo: 'ACC002',
        meterNo: 'MTR002',
        address: '456 Oak St',
        city: 'Metropolis',
        lga: 'LGA2',
        state: 'State2',
        nearestLandmark: 'Near the library',
        date: new Date('2024-09-27'),
        latitude: '13.456789',
        longitude: '97.654321',
        customerId: 'CUST002',
        cin: 'CIN002',
        applicationDate: '2024-02-15',
        mobile: '2345678901',
        email: 'janesmith@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R2',
        correctTariffCode: 'R2',
        tariffClass: 'NMD',
        feeder: 'Feeder2',
        feederId: 'FEED002',
        serviceCenter: 'Center2',
        distributionName: 'Distribution2',
        dssId: 'DSS002',
        ltPoleId: 'LT002',
        serviceWire: 'Wire2',
        upriser: 'Upriser2',
        region: 'Region2',
        businessHub: 'Hub2',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Retail',
        customerNIN: 'NIN002',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '2000',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Pole-Mounted',
        customerMeterManufacturer: 'Manufacturer2',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Jane Smith',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Robert Smith',
        landlordPhone: '321-654-0987',
        tenantName: 'Emily Smith',
        tenantPhone: '234-567-8902',
        meterCTRatio: '1:1',
        status: 'Approved',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1003,
        customerFullName: 'Alice Johnson',
        accountNo: 'ACC003',
        meterNo: 'MTR003',
        address: '789 Pine St',
        city: 'Gotham',
        lga: 'LGA3',
        state: 'State3',
        nearestLandmark: 'Near the school',
        date: new Date('2024-09-27'),
        latitude: '14.567890',
        longitude: '96.543210',
        customerId: 'CUST003',
        cin: 'CIN003',
        applicationDate: '2024-03-15',
        mobile: '3456789012',
        email: 'alicejohnson@example.com',
        statusCode: 'Closed',
        accountType: 'Postpaid',
        currentTariffCode: 'R3',
        correctTariffCode: 'R3',
        tariffClass: 'MD1',
        feeder: 'Feeder3',
        feederId: 'FEED003',
        serviceCenter: 'Center3',
        distributionName: 'Distribution3',
        dssId: 'DSS003',
        ltPoleId: 'LT003',
        serviceWire: 'Wire3',
        upriser: 'Upriser3',
        region: 'Region3',
        businessHub: 'Hub3',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Service',
        customerNIN: 'NIN003',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1500',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Digital',
        customerMeterManufacturer: 'Manufacturer3',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Alice Johnson',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        status: 'Rejected',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1004,
        customerFullName: 'Bob Brown',
        accountNo: 'ACC004',
        meterNo: 'MTR004',
        address: '321 Birch St',
        city: 'Star City',
        lga: 'LGA4',
        state: 'State4',
        nearestLandmark: 'Near the mall',
        latitude: '15.678901',
        longitude: '95.432109',
        customerId: 'CUST004',
        cin: 'CIN004',
        applicationDate: '2024-04-15',
        mobile: '4567890123',
        email: 'bobbrown@example.com',
        statusCode: 'Inactive',
        accountType: 'Prepaid',
        currentTariffCode: 'C1',
        correctTariffCode: 'C1',
        tariffClass: 'MD2',
        feeder: 'Feeder4',
        feederId: 'FEED004',
        serviceCenter: 'Center4',
        distributionName: 'Distribution4',
        dssId: 'DSS004',
        ltPoleId: 'LT004',
        serviceWire: 'Wire4',
        upriser: 'Upriser4',
        region: 'Region4',
        businessHub: 'Hub4',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Wholesale',
        customerNIN: 'NIN004',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '2500',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Wall-mounted',
        customerMeterManufacturer: 'Manufacturer4',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Bob Brown',
        customerHasAccountNo: 'Yes',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Susan Brown',
        landlordPhone: '654-321-0987',
        tenantName: 'Mike Brown',
        tenantPhone: '567-890-1234',
        meterCTRatio: '1:1',
        date: new Date('2024-09-25'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1005,
        customerFullName: 'Charlie Davis',
        accountNo: 'ACC005',
        meterNo: 'MTR005',
        address: '654 Cedar St',
        city: 'Central City',
        lga: 'LGA5',
        state: 'State5',
        nearestLandmark: 'Near the post office',
        latitude: '16.789012',
        longitude: '94.321098',
        customerId: 'CUST005',
        cin: 'CIN005',
        applicationDate: '2024-05-15',
        mobile: '5678901234',
        email: 'charliedavis@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R4',
        correctTariffCode: 'R4',
        tariffClass: 'LFN',
        feeder: 'Feeder5',
        feederId: 'FEED005',
        serviceCenter: 'Center5',
        distributionName: 'Distribution5',
        dssId: 'DSS005',
        ltPoleId: 'LT005',
        serviceWire: 'Wire5',
        upriser: 'Upriser5',
        region: 'Region5',
        businessHub: 'Hub5',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Home',
        customerNIN: 'NIN005',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1200',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Mechanical',
        customerMeterManufacturer: 'Manufacturer5',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Charlie Davis',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-24'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1006,
        customerFullName: 'David Evans',
        accountNo: 'ACC006',
        meterNo: 'MTR006',
        address: '789 Willow St',
        city: 'Coast City',
        lga: 'LGA6',
        state: 'State6',
        nearestLandmark: 'Near the park',
        latitude: '17.890123',
        longitude: '93.210987',
        customerId: 'CUST006',
        cin: 'CIN006',
        applicationDate: '2024-06-15',
        mobile: '6789012345',
        email: 'davidevans@example.com',
        statusCode: 'Inactive',
        accountType: 'Prepaid',
        currentTariffCode: 'R5',
        correctTariffCode: 'R5',
        tariffClass: 'MD2',
        feeder: 'Feeder6',
        feederId: 'FEED006',
        serviceCenter: 'Center6',
        distributionName: 'Distribution6',
        dssId: 'DSS006',
        ltPoleId: 'LT006',
        serviceWire: 'Wire6',
        upriser: 'Upriser6',
        region: 'Region6',
        businessHub: 'Hub6',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Manufacturing',
        customerNIN: 'NIN006',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '3000',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Wall-mounted',
        customerMeterManufacturer: 'Manufacturer6',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'David Evans',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Mark Evans',
        landlordPhone: '890-123-4567',
        tenantName: 'Sarah Evans',
        tenantPhone: '345-678-9012',
        meterCTRatio: '1:1',
        date: new Date('2024-09-23'),
        status: 'Approved',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1007,
        customerFullName: 'Eva Foster',
        accountNo: 'ACC007',
        meterNo: 'MTR007',
        address: '123 Maple St',
        city: 'Gateway City',
        lga: 'LGA7',
        state: 'State7',
        nearestLandmark: 'Near the hospital',
        latitude: '18.901234',
        longitude: '92.109876',
        customerId: 'CUST007',
        cin: 'CIN007',
        applicationDate: '2024-07-15',
        mobile: '7890123456',
        email: 'evafoster@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R6',
        correctTariffCode: 'R6',
        tariffClass: 'LFN',
        feeder: 'Feeder7',
        feederId: 'FEED007',
        serviceCenter: 'Center7',
        distributionName: 'Distribution7',
        dssId: 'DSS007',
        ltPoleId: 'LT007',
        serviceWire: 'Wire7',
        upriser: 'Upriser7',
        region: 'Region7',
        businessHub: 'Hub7',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Retail',
        customerNIN: 'NIN007',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1300',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Electronics',
        customerMeterManufacturer: 'Manufacturer7',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Eva Foster',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-22'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1008,
        customerFullName: 'Frank Green',
        accountNo: 'ACC008',
        meterNo: 'MTR008',
        address: '987 Spruce St',
        city: 'National City',
        lga: 'LGA8',
        state: 'State8',
        nearestLandmark: 'Near the fire station',
        latitude: '19.012345',
        longitude: '91.098765',
        customerId: 'CUST008',
        cin: 'CIN008',
        applicationDate: '2024-08-15',
        mobile: '8901234567',
        email: 'frankgreen@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R7',
        correctTariffCode: 'R7',
        tariffClass: 'MD2',
        feeder: 'Feeder8',
        feederId: 'FEED008',
        serviceCenter: 'Center8',
        distributionName: 'Distribution8',
        dssId: 'DSS008',
        ltPoleId: 'LT008',
        serviceWire: 'Wire8',
        upriser: 'Upriser8',
        region: 'Region8',
        businessHub: 'Hub8',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Hospitality',
        customerNIN: 'NIN008',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '4000',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Wall-mounted',
        customerMeterManufacturer: 'Manufacturer8',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Frank Green',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Helen Green',
        landlordPhone: '012-345-6789',
        tenantName: 'Linda Green',
        tenantPhone: '456-789-0123',
        meterCTRatio: '1:1',
        date: new Date('2024-09-21'),
        status: 'Approved',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1009,
        customerFullName: 'Grace Hall',
        accountNo: 'ACC009',
        meterNo: 'MTR009',
        address: '321 Redwood St',
        city: 'Emerald City',
        lga: 'LGA9',
        state: 'State9',
        nearestLandmark: 'Near the market',
        latitude: '20.123456',
        longitude: '90.987654',
        customerId: 'CUST009',
        cin: 'CIN009',
        applicationDate: '2024-09-15',
        mobile: '9012345678',
        email: 'gracehall@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R8',
        correctTariffCode: 'R8',
        tariffClass: 'LFN',
        feeder: 'Feeder9',
        feederId: 'FEED009',
        serviceCenter: 'Center9',
        distributionName: 'Distribution9',
        dssId: 'DSS009',
        ltPoleId: 'LT009',
        serviceWire: 'Wire9',
        upriser: 'Upriser9',
        region: 'Region9',
        businessHub: 'Hub9',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Education',
        customerNIN: 'NIN009',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1100',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Digital',
        customerMeterManufacturer: 'Manufacturer9',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Grace Hall',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-20'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1010,
        customerFullName: 'Henry Scott',
        accountNo: 'ACC010',
        meterNo: 'MTR010',
        address: '654 Cypress St',
        city: 'Blüdhaven',
        lga: 'LGA10',
        state: 'State10',
        nearestLandmark: 'Near the station',
        latitude: '21.234567',
        longitude: '89.876543',
        customerId: 'CUST010',
        cin: 'CIN010',
        applicationDate: '2024-10-15',
        mobile: '0123456789',
        email: 'henryscott@example.com',
        statusCode: 'Inactive',
        accountType: 'Prepaid',
        currentTariffCode: 'R9',
        correctTariffCode: 'R9',
        tariffClass: 'MD2',
        feeder: 'Feeder10',
        feederId: 'FEED010',
        serviceCenter: 'Center10',
        distributionName: 'Distribution10',
        dssId: 'DSS010',
        ltPoleId: 'LT010',
        serviceWire: 'Wire10',
        upriser: 'Upriser10',
        region: 'Region10',
        businessHub: 'Hub10',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Retail',
        customerNIN: 'NIN010',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '3500',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Pole-mounted',
        customerMeterManufacturer: 'Manufacturer10',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Henry Scott',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Margaret Scott',
        landlordPhone: '789-012-3456',
        tenantName: 'John Scott',
        tenantPhone: '890-123-4567',
        meterCTRatio: '1:1',
        date: new Date('2024-09-19'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1011,
        customerFullName: 'Isabella Thompson',
        accountNo: 'ACC011',
        meterNo: 'MTR011',
        address: '432 Oakwood St',
        city: 'River City',
        lga: 'LGA11',
        state: 'State11',
        nearestLandmark: 'Near the church',
        latitude: '22.345678',
        longitude: '88.765432',
        customerId: 'CUST011',
        cin: 'CIN011',
        applicationDate: '2024-10-01',
        mobile: '1234567890',
        email: 'isabellathompson@example.com',
        statusCode: 'Suspended',
        accountType: 'Postpaid',
        currentTariffCode: 'R10',
        correctTariffCode: 'R10',
        tariffClass: 'LFN',
        feeder: 'Feeder11',
        feederId: 'FEED011',
        serviceCenter: 'Center11',
        distributionName: 'Distribution11',
        dssId: 'DSS011',
        ltPoleId: 'LT011',
        serviceWire: 'Wire11',
        upriser: 'Upriser11',
        region: 'Region11',
        businessHub: 'Hub11',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Education',
        customerNIN: 'NIN011',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '900',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Electronics',
        customerMeterManufacturer: 'Manufacturer11',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Isabella Thompson',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-18'),
        status: 'Approved',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1012,
        customerFullName: 'Jack White',
        accountNo: 'ACC012',
        meterNo: 'MTR012',
        address: '765 Birch St',
        city: 'Central City',
        lga: 'LGA12',
        state: 'State12',
        nearestLandmark: 'Near the bus depot',
        latitude: '23.456789',
        longitude: '87.654321',
        customerId: 'CUST012',
        cin: 'CIN012',
        applicationDate: '2024-09-22',
        mobile: '2345678901',
        email: 'jackwhite@example.com',
        statusCode: 'Active',
        accountType: 'Prepaid',
        currentTariffCode: 'R11',
        correctTariffCode: 'R11',
        tariffClass: 'MD2',
        feeder: 'Feeder12',
        feederId: 'FEED012',
        serviceCenter: 'Center12',
        distributionName: 'Distribution12',
        dssId: 'DSS012',
        ltPoleId: 'LT012',
        serviceWire: 'Wire12',
        upriser: 'Upriser12',
        region: 'Region12',
        businessHub: 'Hub12',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Manufacturing',
        customerNIN: 'NIN012',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '4500',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Prepaid - Digital',
        customerMeterManufacturer: 'Manufacturer12',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Jack White',
        customerHasAccountNo: 'Yes',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Amanda White',
        landlordPhone: '567-890-1234',
        tenantName: 'Peter White',
        tenantPhone: '345-678-9012',
        meterCTRatio: '1:1',
        date: new Date('2024-09-17'),
        status: 'Approved',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1013,
        customerFullName: 'Kelly Black',
        accountNo: 'ACC013',
        meterNo: 'MTR013',
        address: '987 Pine St',
        city: 'Star City',
        lga: 'LGA13',
        state: 'State13',
        nearestLandmark: 'Near the school',
        latitude: '24.567890',
        longitude: '86.543210',
        customerId: 'CUST013',
        cin: 'CIN013',
        applicationDate: '2024-10-02',
        mobile: '3456789012',
        email: 'kellyblack@example.com',
        statusCode: 'Inactive',
        accountType: 'Postpaid',
        currentTariffCode: 'R12',
        correctTariffCode: 'R12',
        tariffClass: 'LFN',
        feeder: 'Feeder13',
        feederId: 'FEED013',
        serviceCenter: 'Center13',
        distributionName: 'Distribution13',
        dssId: 'DSS013',
        ltPoleId: 'LT013',
        serviceWire: 'Wire13',
        upriser: 'Upriser13',
        region: 'Region13',
        businessHub: 'Hub13',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Education',
        customerNIN: 'NIN013',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1000',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Mechanical',
        customerMeterManufacturer: 'Manufacturer13',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Kelly Black',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-16'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1014,
        customerFullName: 'Leo Brown',
        accountNo: 'ACC014',
        meterNo: 'MTR014',
        address: '123 Elm St',
        city: 'Smallville',
        lga: 'LGA14',
        state: 'State14',
        nearestLandmark: 'Near the bank',
        latitude: '25.678901',
        longitude: '85.432109',
        customerId: 'CUST014',
        cin: 'CIN014',
        applicationDate: '2024-10-10',
        mobile: '4567890123',
        email: 'leobrown@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R13',
        correctTariffCode: 'R13',
        tariffClass: 'MD2',
        feeder: 'Feeder14',
        feederId: 'FEED014',
        serviceCenter: 'Center14',
        distributionName: 'Distribution14',
        dssId: 'DSS014',
        ltPoleId: 'LT014',
        serviceWire: 'Wire14',
        upriser: 'Upriser14',
        region: 'Region14',
        businessHub: 'Hub14',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Agriculture',
        customerNIN: 'NIN014',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '5000',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Smart',
        customerMeterManufacturer: 'Manufacturer14',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Leo Brown',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Sarah Brown',
        landlordPhone: '890-123-4567',
        tenantName: 'Liam Brown',
        tenantPhone: '678-901-2345',
        meterCTRatio: '1:1',
        date: new Date('2024-09-15'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1015,
        customerFullName: 'Maria Davis',
        accountNo: 'ACC015',
        meterNo: 'MTR015',
        address: '246 Maple St',
        city: 'Coast City',
        lga: 'LGA15',
        state: 'State15',
        nearestLandmark: 'Near the hospital',
        latitude: '26.789012',
        longitude: '84.321098',
        customerId: 'CUST015',
        cin: 'CIN015',
        applicationDate: '2024-10-05',
        mobile: '5678901234',
        email: 'mariadavis@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R14',
        correctTariffCode: 'R14',
        tariffClass: 'LFN',
        feeder: 'Feeder15',
        feederId: 'FEED015',
        serviceCenter: 'Center15',
        distributionName: 'Distribution15',
        dssId: 'DSS015',
        ltPoleId: 'LT015',
        serviceWire: 'Wire15',
        upriser: 'Upriser15',
        region: 'Region15',
        businessHub: 'Hub15',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Healthcare',
        customerNIN: 'NIN015',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1500',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Electronics',
        customerMeterManufacturer: 'Manufacturer15',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Maria Davis',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-14'),
        status: 'Approved',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1016,
        customerFullName: 'Nancy Clark',
        accountNo: 'ACC016',
        meterNo: 'MTR016',
        address: '789 Willow St',
        city: 'Metropolis',
        lga: 'LGA16',
        state: 'State16',
        nearestLandmark: 'Near the university',
        latitude: '27.890123',
        longitude: '83.210987',
        customerId: 'CUST016',
        cin: 'CIN016',
        applicationDate: '2024-10-09',
        mobile: '6789012345',
        email: 'nancyclark@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R15',
        correctTariffCode: 'R15',
        tariffClass: 'MD1',
        feeder: 'Feeder16',
        feederId: 'FEED016',
        serviceCenter: 'Center16',
        distributionName: 'Distribution16',
        dssId: 'DSS016',
        ltPoleId: 'LT016',
        serviceWire: 'Wire16',
        upriser: 'Upriser16',
        region: 'Region16',
        businessHub: 'Hub16',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Education',
        customerNIN: 'NIN016',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '4000',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Prepaid - Analog',
        customerMeterManufacturer: 'Manufacturer16',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Nancy Clark',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'Yes',
        landlordName: 'John Clark',
        landlordPhone: '789-012-3456',
        tenantName: 'Emma Clark',
        tenantPhone: '890-123-4567',
        meterCTRatio: '1:1',
        date: new Date('2024-09-13'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1017,
        customerFullName: 'Oliver Evans',
        accountNo: 'ACC017',
        meterNo: 'MTR017',
        address: '135 Oak St',
        city: 'Gotham City',
        lga: 'LGA17',
        state: 'State17',
        nearestLandmark: 'Near the police station',
        latitude: '28.901234',
        longitude: '82.109876',
        customerId: 'CUST017',
        cin: 'CIN017',
        applicationDate: '2024-10-12',
        mobile: '7890123456',
        email: 'oliverevans@example.com',
        statusCode: 'Inactive',
        accountType: 'Postpaid',
        currentTariffCode: 'R16',
        correctTariffCode: 'R16',
        tariffClass: 'LFN',
        feeder: 'Feeder17',
        feederId: 'FEED017',
        serviceCenter: 'Center17',
        distributionName: 'Distribution17',
        dssId: 'DSS017',
        ltPoleId: 'LT017',
        serviceWire: 'Wire17',
        upriser: 'Upriser17',
        region: 'Region17',
        businessHub: 'Hub17',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Retail',
        customerNIN: 'NIN017',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1200',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Mechanical',
        customerMeterManufacturer: 'Manufacturer17',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Oliver Evans',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-12'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1018,
        customerFullName: 'Grace Wilson',
        accountNo: 'ACC018',
        meterNo: 'MTR018',
        address: '987 Cedar St',
        city: 'Coast City',
        lga: 'LGA18',
        state: 'State18',
        nearestLandmark: 'Near the cinema',
        latitude: '29.012345',
        longitude: '81.098765',
        customerId: 'CUST018',
        cin: 'CIN018',
        applicationDate: '2024-09-30',
        mobile: '8901234567',
        email: 'gracewilson@example.com',
        statusCode: 'Active',
        accountType: 'Prepaid',
        currentTariffCode: 'R17',
        correctTariffCode: 'R17',
        tariffClass: 'MD1',
        feeder: 'Feeder18',
        feederId: 'FEED018',
        serviceCenter: 'Center18',
        distributionName: 'Distribution18',
        dssId: 'DSS018',
        ltPoleId: 'LT018',
        serviceWire: 'Wire18',
        upriser: 'Upriser18',
        region: 'Region18',
        businessHub: 'Hub18',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Real Estate',
        customerNIN: 'NIN018',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '4200',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Prepaid - Smart',
        customerMeterManufacturer: 'Manufacturer18',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Grace Wilson',
        customerHasAccountNo: 'Yes',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'James Wilson',
        landlordPhone: '901-234-5678',
        tenantName: 'Lily Wilson',
        tenantPhone: '345-678-9012',
        meterCTRatio: '1:1',
        date: new Date('2024-09-10'),
        status: 'Approved',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1019,
        customerFullName: 'Henry Morgan',
        accountNo: 'ACC019',
        meterNo: 'MTR019',
        address: '654 Birch St',
        city: 'Star City',
        lga: 'LGA19',
        state: 'State19',
        nearestLandmark: 'Near the shopping mall',
        latitude: '30.123456',
        longitude: '80.987654',
        customerId: 'CUST019',
        cin: 'CIN019',
        applicationDate: '2024-10-11',
        mobile: '9012345678',
        email: 'henrymorgan@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R18',
        correctTariffCode: 'R18',
        tariffClass: 'LFN',
        feeder: 'Feeder19',
        feederId: 'FEED019',
        serviceCenter: 'Center19',
        distributionName: 'Distribution19',
        dssId: 'DSS019',
        ltPoleId: 'LT019',
        serviceWire: 'Wire19',
        upriser: 'Upriser19',
        region: 'Region19',
        businessHub: 'Hub19',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Hospitality',
        customerNIN: 'NIN019',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1800',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Analog',
        customerMeterManufacturer: 'Manufacturer19',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Henry Morgan',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-09'),
        status: 'Approved',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1020,
        customerFullName: 'Sophia Adams',
        accountNo: 'ACC020',
        meterNo: 'MTR020',
        address: '321 Walnut St',
        city: 'Smallville',
        lga: 'LGA20',
        state: 'State20',
        nearestLandmark: 'Near the market',
        latitude: '31.234567',
        longitude: '79.876543',
        customerId: 'CUST020',
        cin: 'CIN020',
        applicationDate: '2024-10-08',
        mobile: '0123456789',
        email: 'sophiaadams@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R19',
        correctTariffCode: 'R19',
        tariffClass: 'MD2',
        feeder: 'Feeder20',
        feederId: 'FEED020',
        serviceCenter: 'Center20',
        distributionName: 'Distribution20',
        dssId: 'DSS020',
        ltPoleId: 'LT020',
        serviceWire: 'Wire20',
        upriser: 'Upriser20',
        region: 'Region20',
        businessHub: 'Hub20',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Construction',
        customerNIN: 'NIN020',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '5500',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Smart',
        customerMeterManufacturer: 'Manufacturer20',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Sophia Adams',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'William Adams',
        landlordPhone: '234-567-8901',
        tenantName: 'Olivia Adams',
        tenantPhone: '678-901-2345',
        meterCTRatio: '1:1',
        date: new Date('2024-09-08'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1021,
        customerFullName: 'James Bailey',
        accountNo: 'ACC021',
        meterNo: 'MTR021',
        address: '456 Maple St',
        city: 'Metropolis',
        lga: 'LGA21',
        state: 'State21',
        nearestLandmark: 'Near the train station',
        latitude: '32.345678',
        longitude: '78.765432',
        customerId: 'CUST021',
        cin: 'CIN021',
        applicationDate: '2024-09-28',
        mobile: '1234567890',
        email: 'jamesbailey@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R20',
        correctTariffCode: 'R20',
        tariffClass: 'MD1',
        feeder: 'Feeder21',
        feederId: 'FEED021',
        serviceCenter: 'Center21',
        distributionName: 'Distribution21',
        dssId: 'DSS021',
        ltPoleId: 'LT021',
        serviceWire: 'Wire21',
        upriser: 'Upriser21',
        region: 'Region21',
        businessHub: 'Hub21',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Entertainment',
        customerNIN: 'NIN021',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1600',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Analog',
        customerMeterManufacturer: 'Manufacturer21',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'James Bailey',
        customerHasAccountNo: 'Yes',
        customerGroup: 'Existing',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-07'),
        status: 'Approved',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1022,
        customerFullName: 'Isabella Scott',
        accountNo: 'ACC022',
        meterNo: 'MTR022',
        address: '789 Elm St',
        city: 'Central City',
        lga: 'LGA22',
        state: 'State22',
        nearestLandmark: 'Near the library',
        latitude: '33.456789',
        longitude: '77.654321',
        customerId: 'CUST022',
        cin: 'CIN022',
        applicationDate: '2024-09-26',
        mobile: '2345678901',
        email: 'isabellascott@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R21',
        correctTariffCode: 'R21',
        tariffClass: 'MD2',
        feeder: 'Feeder22',
        feederId: 'FEED022',
        serviceCenter: 'Center22',
        distributionName: 'Distribution22',
        dssId: 'DSS022',
        ltPoleId: 'LT022',
        serviceWire: 'Wire22',
        upriser: 'Upriser22',
        region: 'Region22',
        businessHub: 'Hub22',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Manufacturing',
        customerNIN: 'NIN022',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '3600',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Prepaid - Smart',
        customerMeterManufacturer: 'Manufacturer22',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Isabella Scott',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'Yes',
        landlordName: 'Michael Scott',
        landlordPhone: '345-678-9012',
        tenantName: 'Sophia Scott',
        tenantPhone: '567-890-1234',
        meterCTRatio: '1:1',
        date: new Date('2024-09-06'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1023,
        customerFullName: 'Lucas Miller',
        accountNo: 'ACC023',
        meterNo: 'MTR023',
        address: '321 Pine St',
        city: 'National City',
        lga: 'LGA23',
        state: 'State23',
        nearestLandmark: 'Near the university',
        latitude: '34.567890',
        longitude: '76.543210',
        customerId: 'CUST023',
        cin: 'CIN023',
        applicationDate: '2024-09-24',
        mobile: '3456789012',
        email: 'lucasmiller@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R22',
        correctTariffCode: 'R22',
        tariffClass: 'LFN',
        feeder: 'Feeder23',
        feederId: 'FEED023',
        serviceCenter: 'Center23',
        distributionName: 'Distribution23',
        dssId: 'DSS023',
        ltPoleId: 'LT023',
        serviceWire: 'Wire23',
        upriser: 'Upriser23',
        region: 'Region23',
        businessHub: 'Hub23',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Automotive',
        customerNIN: 'NIN023',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1400',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Mechanical',
        customerMeterManufacturer: 'Manufacturer23',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Lucas Miller',
        customerHasAccountNo: 'Yes',
        customerGroup: 'Existing',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-05'),
        status: 'Approved',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1024,
        customerFullName: 'Emma Walker',
        accountNo: 'ACC024',
        meterNo: 'MTR024',
        address: '654 Poplar St',
        city: 'Opal City',
        lga: 'LGA24',
        state: 'State24',
        nearestLandmark: 'Near the fire station',
        latitude: '35.678901',
        longitude: '75.432109',
        customerId: 'CUST024',
        cin: 'CIN024',
        applicationDate: '2024-09-22',
        mobile: '4567890123',
        email: 'emmawalker@example.com',
        statusCode: 'Inactive',
        accountType: 'Prepaid',
        currentTariffCode: 'R23',
        correctTariffCode: 'R23',
        tariffClass: 'MD1',
        feeder: 'Feeder24',
        feederId: 'FEED024',
        serviceCenter: 'Center24',
        distributionName: 'Distribution24',
        dssId: 'DSS024',
        ltPoleId: 'LT024',
        serviceWire: 'Wire24',
        upriser: 'Upriser24',
        region: 'Region24',
        businessHub: 'Hub24',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Retail',
        customerNIN: 'NIN024',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '3200',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Prepaid - Smart',
        customerMeterManufacturer: 'Manufacturer24',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Emma Walker',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'Yes',
        landlordName: 'Robert Walker',
        landlordPhone: '678-901-2345',
        tenantName: 'Ava Walker',
        tenantPhone: '890-123-4567',
        meterCTRatio: '1:1',
        date: new Date('2024-09-04'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
    ];
  }


  getNewCustomers(): Customer[] {
    return [
      {
        id: 1001,
        customerFullName: 'John Doe',
        accountNo: 'ACC001',
        meterNo: 'MTR001',
        address: '123 Elm St',
        city: 'Springfield',
        lga: 'LGA1',
        state: 'State1',
        nearestLandmark: 'Near the park',
        date: new Date('2024-09-27'),
        latitude: '12.345678',
        longitude: '98.765432',
        customerId: 'CUST001',
        cin: 'CIN001',
        applicationDate: '2024-01-15',
        mobile: '1234567890',
        email: 'johndoe@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R1',
        correctTariffCode: 'R1',
        tariffClass: 'LFN',
        feeder: 'Feeder1',
        feederId: 'FEED001',
        serviceCenter: 'Center1',
        distributionName: 'Distribution1',
        dssId: 'DSS001',
        ltPoleId: 'LT001',
        serviceWire: 'Wire1',
        upriser: 'Upriser1',
        region: 'Region1',
        businessHub: 'Hub1',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Business',
        customerNIN: 'NIN001',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1000',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Electronics',
        customerMeterManufacturer: 'Manufacturer1',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'John Doe',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1002,
        customerFullName: 'Jane Smith',
        accountNo: 'ACC002',
        meterNo: 'MTR002',
        address: '456 Oak St',
        city: 'Metropolis',
        lga: 'LGA2',
        state: 'State2',
        nearestLandmark: 'Near the library',
        date: new Date('2024-09-27'),
        latitude: '13.456789',
        longitude: '97.654321',
        customerId: 'CUST002',
        cin: 'CIN002',
        applicationDate: '2024-02-15',
        mobile: '2345678901',
        email: 'janesmith@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R2',
        correctTariffCode: 'R2',
        tariffClass: 'NMD',
        feeder: 'Feeder2',
        feederId: 'FEED002',
        serviceCenter: 'Center2',
        distributionName: 'Distribution2',
        dssId: 'DSS002',
        ltPoleId: 'LT002',
        serviceWire: 'Wire2',
        upriser: 'Upriser2',
        region: 'Region2',
        businessHub: 'Hub2',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Retail',
        customerNIN: 'NIN002',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '2000',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Pole-Mounted',
        customerMeterManufacturer: 'Manufacturer2',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Jane Smith',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Robert Smith',
        landlordPhone: '321-654-0987',
        tenantName: 'Emily Smith',
        tenantPhone: '234-567-8902',
        meterCTRatio: '1:1',
        status: 'Approved',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1003,
        customerFullName: 'Alice Johnson',
        accountNo: 'ACC003',
        meterNo: 'MTR003',
        address: '789 Pine St',
        city: 'Gotham',
        lga: 'LGA3',
        state: 'State3',
        nearestLandmark: 'Near the school',
        date: new Date('2024-09-27'),
        latitude: '14.567890',
        longitude: '96.543210',
        customerId: 'CUST003',
        cin: 'CIN003',
        applicationDate: '2024-03-15',
        mobile: '3456789012',
        email: 'alicejohnson@example.com',
        statusCode: 'Closed',
        accountType: 'Postpaid',
        currentTariffCode: 'R3',
        correctTariffCode: 'R3',
        tariffClass: 'MD1',
        feeder: 'Feeder3',
        feederId: 'FEED003',
        serviceCenter: 'Center3',
        distributionName: 'Distribution3',
        dssId: 'DSS003',
        ltPoleId: 'LT003',
        serviceWire: 'Wire3',
        upriser: 'Upriser3',
        region: 'Region3',
        businessHub: 'Hub3',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Service',
        customerNIN: 'NIN003',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1500',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Digital',
        customerMeterManufacturer: 'Manufacturer3',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Alice Johnson',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        status: 'Rejected',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1004,
        customerFullName: 'Bob Brown',
        accountNo: 'ACC004',
        meterNo: 'MTR004',
        address: '321 Birch St',
        city: 'Star City',
        lga: 'LGA4',
        state: 'State4',
        nearestLandmark: 'Near the mall',
        latitude: '15.678901',
        longitude: '95.432109',
        customerId: 'CUST004',
        cin: 'CIN004',
        applicationDate: '2024-04-15',
        mobile: '4567890123',
        email: 'bobbrown@example.com',
        statusCode: 'Inactive',
        accountType: 'Prepaid',
        currentTariffCode: 'C1',
        correctTariffCode: 'C1',
        tariffClass: 'MD2',
        feeder: 'Feeder4',
        feederId: 'FEED004',
        serviceCenter: 'Center4',
        distributionName: 'Distribution4',
        dssId: 'DSS004',
        ltPoleId: 'LT004',
        serviceWire: 'Wire4',
        upriser: 'Upriser4',
        region: 'Region4',
        businessHub: 'Hub4',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Wholesale',
        customerNIN: 'NIN004',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '2500',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Wall-mounted',
        customerMeterManufacturer: 'Manufacturer4',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Bob Brown',
        customerHasAccountNo: 'Yes',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Susan Brown',
        landlordPhone: '654-321-0987',
        tenantName: 'Mike Brown',
        tenantPhone: '567-890-1234',
        meterCTRatio: '1:1',
        date: new Date('2024-09-25'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1005,
        customerFullName: 'Charlie Davis',
        accountNo: 'ACC005',
        meterNo: 'MTR005',
        address: '654 Cedar St',
        city: 'Central City',
        lga: 'LGA5',
        state: 'State5',
        nearestLandmark: 'Near the post office',
        latitude: '16.789012',
        longitude: '94.321098',
        customerId: 'CUST005',
        cin: 'CIN005',
        applicationDate: '2024-05-15',
        mobile: '5678901234',
        email: 'charliedavis@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R4',
        correctTariffCode: 'R4',
        tariffClass: 'LFN',
        feeder: 'Feeder5',
        feederId: 'FEED005',
        serviceCenter: 'Center5',
        distributionName: 'Distribution5',
        dssId: 'DSS005',
        ltPoleId: 'LT005',
        serviceWire: 'Wire5',
        upriser: 'Upriser5',
        region: 'Region5',
        businessHub: 'Hub5',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Home',
        customerNIN: 'NIN005',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1200',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Mechanical',
        customerMeterManufacturer: 'Manufacturer5',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Charlie Davis',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-24'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1006,
        customerFullName: 'David Evans',
        accountNo: 'ACC006',
        meterNo: 'MTR006',
        address: '789 Willow St',
        city: 'Coast City',
        lga: 'LGA6',
        state: 'State6',
        nearestLandmark: 'Near the park',
        latitude: '17.890123',
        longitude: '93.210987',
        customerId: 'CUST006',
        cin: 'CIN006',
        applicationDate: '2024-06-15',
        mobile: '6789012345',
        email: 'davidevans@example.com',
        statusCode: 'Inactive',
        accountType: 'Prepaid',
        currentTariffCode: 'R5',
        correctTariffCode: 'R5',
        tariffClass: 'MD2',
        feeder: 'Feeder6',
        feederId: 'FEED006',
        serviceCenter: 'Center6',
        distributionName: 'Distribution6',
        dssId: 'DSS006',
        ltPoleId: 'LT006',
        serviceWire: 'Wire6',
        upriser: 'Upriser6',
        region: 'Region6',
        businessHub: 'Hub6',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Manufacturing',
        customerNIN: 'NIN006',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '3000',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Wall-mounted',
        customerMeterManufacturer: 'Manufacturer6',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'David Evans',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Mark Evans',
        landlordPhone: '890-123-4567',
        tenantName: 'Sarah Evans',
        tenantPhone: '345-678-9012',
        meterCTRatio: '1:1',
        date: new Date('2024-09-23'),
        status: 'Approved',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1007,
        customerFullName: 'Eva Foster',
        accountNo: 'ACC007',
        meterNo: 'MTR007',
        address: '123 Maple St',
        city: 'Gateway City',
        lga: 'LGA7',
        state: 'State7',
        nearestLandmark: 'Near the hospital',
        latitude: '18.901234',
        longitude: '92.109876',
        customerId: 'CUST007',
        cin: 'CIN007',
        applicationDate: '2024-07-15',
        mobile: '7890123456',
        email: 'evafoster@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R6',
        correctTariffCode: 'R6',
        tariffClass: 'LFN',
        feeder: 'Feeder7',
        feederId: 'FEED007',
        serviceCenter: 'Center7',
        distributionName: 'Distribution7',
        dssId: 'DSS007',
        ltPoleId: 'LT007',
        serviceWire: 'Wire7',
        upriser: 'Upriser7',
        region: 'Region7',
        businessHub: 'Hub7',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Retail',
        customerNIN: 'NIN007',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1300',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Electronics',
        customerMeterManufacturer: 'Manufacturer7',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Eva Foster',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-22'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1008,
        customerFullName: 'Frank Green',
        accountNo: 'ACC008',
        meterNo: 'MTR008',
        address: '987 Spruce St',
        city: 'National City',
        lga: 'LGA8',
        state: 'State8',
        nearestLandmark: 'Near the fire station',
        latitude: '19.012345',
        longitude: '91.098765',
        customerId: 'CUST008',
        cin: 'CIN008',
        applicationDate: '2024-08-15',
        mobile: '8901234567',
        email: 'frankgreen@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R7',
        correctTariffCode: 'R7',
        tariffClass: 'MD2',
        feeder: 'Feeder8',
        feederId: 'FEED008',
        serviceCenter: 'Center8',
        distributionName: 'Distribution8',
        dssId: 'DSS008',
        ltPoleId: 'LT008',
        serviceWire: 'Wire8',
        upriser: 'Upriser8',
        region: 'Region8',
        businessHub: 'Hub8',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Hospitality',
        customerNIN: 'NIN008',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '4000',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Wall-mounted',
        customerMeterManufacturer: 'Manufacturer8',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Frank Green',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Helen Green',
        landlordPhone: '012-345-6789',
        tenantName: 'Linda Green',
        tenantPhone: '456-789-0123',
        meterCTRatio: '1:1',
        date: new Date('2024-09-21'),
        status: 'Approved',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1009,
        customerFullName: 'Grace Hall',
        accountNo: 'ACC009',
        meterNo: 'MTR009',
        address: '321 Redwood St',
        city: 'Emerald City',
        lga: 'LGA9',
        state: 'State9',
        nearestLandmark: 'Near the market',
        latitude: '20.123456',
        longitude: '90.987654',
        customerId: 'CUST009',
        cin: 'CIN009',
        applicationDate: '2024-09-15',
        mobile: '9012345678',
        email: 'gracehall@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R8',
        correctTariffCode: 'R8',
        tariffClass: 'LFN',
        feeder: 'Feeder9',
        feederId: 'FEED009',
        serviceCenter: 'Center9',
        distributionName: 'Distribution9',
        dssId: 'DSS009',
        ltPoleId: 'LT009',
        serviceWire: 'Wire9',
        upriser: 'Upriser9',
        region: 'Region9',
        businessHub: 'Hub9',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Education',
        customerNIN: 'NIN009',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1100',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Digital',
        customerMeterManufacturer: 'Manufacturer9',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Grace Hall',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-20'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1010,
        customerFullName: 'Henry Scott',
        accountNo: 'ACC010',
        meterNo: 'MTR010',
        address: '654 Cypress St',
        city: 'Blüdhaven',
        lga: 'LGA10',
        state: 'State10',
        nearestLandmark: 'Near the station',
        latitude: '21.234567',
        longitude: '89.876543',
        customerId: 'CUST010',
        cin: 'CIN010',
        applicationDate: '2024-10-15',
        mobile: '0123456789',
        email: 'henryscott@example.com',
        statusCode: 'Inactive',
        accountType: 'Prepaid',
        currentTariffCode: 'R9',
        correctTariffCode: 'R9',
        tariffClass: 'MD2',
        feeder: 'Feeder10',
        feederId: 'FEED010',
        serviceCenter: 'Center10',
        distributionName: 'Distribution10',
        dssId: 'DSS010',
        ltPoleId: 'LT010',
        serviceWire: 'Wire10',
        upriser: 'Upriser10',
        region: 'Region10',
        businessHub: 'Hub10',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Retail',
        customerNIN: 'NIN010',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '3500',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Pole-mounted',
        customerMeterManufacturer: 'Manufacturer10',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Henry Scott',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Margaret Scott',
        landlordPhone: '789-012-3456',
        tenantName: 'John Scott',
        tenantPhone: '890-123-4567',
        meterCTRatio: '1:1',
        date: new Date('2024-09-19'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1011,
        customerFullName: 'Isabella Thompson',
        accountNo: 'ACC011',
        meterNo: 'MTR011',
        address: '432 Oakwood St',
        city: 'River City',
        lga: 'LGA11',
        state: 'State11',
        nearestLandmark: 'Near the church',
        latitude: '22.345678',
        longitude: '88.765432',
        customerId: 'CUST011',
        cin: 'CIN011',
        applicationDate: '2024-10-01',
        mobile: '1234567890',
        email: 'isabellathompson@example.com',
        statusCode: 'Suspended',
        accountType: 'Postpaid',
        currentTariffCode: 'R10',
        correctTariffCode: 'R10',
        tariffClass: 'LFN',
        feeder: 'Feeder11',
        feederId: 'FEED011',
        serviceCenter: 'Center11',
        distributionName: 'Distribution11',
        dssId: 'DSS011',
        ltPoleId: 'LT011',
        serviceWire: 'Wire11',
        upriser: 'Upriser11',
        region: 'Region11',
        businessHub: 'Hub11',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Education',
        customerNIN: 'NIN011',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '900',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Electronics',
        customerMeterManufacturer: 'Manufacturer11',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Isabella Thompson',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-18'),
        status: 'Approved',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1012,
        customerFullName: 'Jack White',
        accountNo: 'ACC012',
        meterNo: 'MTR012',
        address: '765 Birch St',
        city: 'Central City',
        lga: 'LGA12',
        state: 'State12',
        nearestLandmark: 'Near the bus depot',
        latitude: '23.456789',
        longitude: '87.654321',
        customerId: 'CUST012',
        cin: 'CIN012',
        applicationDate: '2024-09-22',
        mobile: '2345678901',
        email: 'jackwhite@example.com',
        statusCode: 'Active',
        accountType: 'Prepaid',
        currentTariffCode: 'R11',
        correctTariffCode: 'R11',
        tariffClass: 'MD2',
        feeder: 'Feeder12',
        feederId: 'FEED012',
        serviceCenter: 'Center12',
        distributionName: 'Distribution12',
        dssId: 'DSS012',
        ltPoleId: 'LT012',
        serviceWire: 'Wire12',
        upriser: 'Upriser12',
        region: 'Region12',
        businessHub: 'Hub12',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Manufacturing',
        customerNIN: 'NIN012',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '4500',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Prepaid - Digital',
        customerMeterManufacturer: 'Manufacturer12',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Jack White',
        customerHasAccountNo: 'Yes',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Amanda White',
        landlordPhone: '567-890-1234',
        tenantName: 'Peter White',
        tenantPhone: '345-678-9012',
        meterCTRatio: '1:1',
        date: new Date('2024-09-17'),
        status: 'Approved',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1013,
        customerFullName: 'Kelly Black',
        accountNo: 'ACC013',
        meterNo: 'MTR013',
        address: '987 Pine St',
        city: 'Star City',
        lga: 'LGA13',
        state: 'State13',
        nearestLandmark: 'Near the school',
        latitude: '24.567890',
        longitude: '86.543210',
        customerId: 'CUST013',
        cin: 'CIN013',
        applicationDate: '2024-10-02',
        mobile: '3456789012',
        email: 'kellyblack@example.com',
        statusCode: 'Inactive',
        accountType: 'Postpaid',
        currentTariffCode: 'R12',
        correctTariffCode: 'R12',
        tariffClass: 'LFN',
        feeder: 'Feeder13',
        feederId: 'FEED013',
        serviceCenter: 'Center13',
        distributionName: 'Distribution13',
        dssId: 'DSS013',
        ltPoleId: 'LT013',
        serviceWire: 'Wire13',
        upriser: 'Upriser13',
        region: 'Region13',
        businessHub: 'Hub13',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Education',
        customerNIN: 'NIN013',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1000',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Mechanical',
        customerMeterManufacturer: 'Manufacturer13',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Kelly Black',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-16'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1014,
        customerFullName: 'Leo Brown',
        accountNo: 'ACC014',
        meterNo: 'MTR014',
        address: '123 Elm St',
        city: 'Smallville',
        lga: 'LGA14',
        state: 'State14',
        nearestLandmark: 'Near the bank',
        latitude: '25.678901',
        longitude: '85.432109',
        customerId: 'CUST014',
        cin: 'CIN014',
        applicationDate: '2024-10-10',
        mobile: '4567890123',
        email: 'leobrown@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R13',
        correctTariffCode: 'R13',
        tariffClass: 'MD2',
        feeder: 'Feeder14',
        feederId: 'FEED014',
        serviceCenter: 'Center14',
        distributionName: 'Distribution14',
        dssId: 'DSS014',
        ltPoleId: 'LT014',
        serviceWire: 'Wire14',
        upriser: 'Upriser14',
        region: 'Region14',
        businessHub: 'Hub14',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Agriculture',
        customerNIN: 'NIN014',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '5000',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Smart',
        customerMeterManufacturer: 'Manufacturer14',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Leo Brown',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'Sarah Brown',
        landlordPhone: '890-123-4567',
        tenantName: 'Liam Brown',
        tenantPhone: '678-901-2345',
        meterCTRatio: '1:1',
        date: new Date('2024-09-15'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1015,
        customerFullName: 'Maria Davis',
        accountNo: 'ACC015',
        meterNo: 'MTR015',
        address: '246 Maple St',
        city: 'Coast City',
        lga: 'LGA15',
        state: 'State15',
        nearestLandmark: 'Near the hospital',
        latitude: '26.789012',
        longitude: '84.321098',
        customerId: 'CUST015',
        cin: 'CIN015',
        applicationDate: '2024-10-05',
        mobile: '5678901234',
        email: 'mariadavis@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R14',
        correctTariffCode: 'R14',
        tariffClass: 'LFN',
        feeder: 'Feeder15',
        feederId: 'FEED015',
        serviceCenter: 'Center15',
        distributionName: 'Distribution15',
        dssId: 'DSS015',
        ltPoleId: 'LT015',
        serviceWire: 'Wire15',
        upriser: 'Upriser15',
        region: 'Region15',
        businessHub: 'Hub15',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Healthcare',
        customerNIN: 'NIN015',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1500',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Electronics',
        customerMeterManufacturer: 'Manufacturer15',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Maria Davis',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-14'),
        status: 'Approved',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1016,
        customerFullName: 'Nancy Clark',
        accountNo: 'ACC016',
        meterNo: 'MTR016',
        address: '789 Willow St',
        city: 'Metropolis',
        lga: 'LGA16',
        state: 'State16',
        nearestLandmark: 'Near the university',
        latitude: '27.890123',
        longitude: '83.210987',
        customerId: 'CUST016',
        cin: 'CIN016',
        applicationDate: '2024-10-09',
        mobile: '6789012345',
        email: 'nancyclark@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R15',
        correctTariffCode: 'R15',
        tariffClass: 'MD1',
        feeder: 'Feeder16',
        feederId: 'FEED016',
        serviceCenter: 'Center16',
        distributionName: 'Distribution16',
        dssId: 'DSS016',
        ltPoleId: 'LT016',
        serviceWire: 'Wire16',
        upriser: 'Upriser16',
        region: 'Region16',
        businessHub: 'Hub16',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Education',
        customerNIN: 'NIN016',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '4000',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Prepaid - Analog',
        customerMeterManufacturer: 'Manufacturer16',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Nancy Clark',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'Yes',
        landlordName: 'John Clark',
        landlordPhone: '789-012-3456',
        tenantName: 'Emma Clark',
        tenantPhone: '890-123-4567',
        meterCTRatio: '1:1',
        date: new Date('2024-09-13'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1017,
        customerFullName: 'Oliver Evans',
        accountNo: 'ACC017',
        meterNo: 'MTR017',
        address: '135 Oak St',
        city: 'Gotham City',
        lga: 'LGA17',
        state: 'State17',
        nearestLandmark: 'Near the police station',
        latitude: '28.901234',
        longitude: '82.109876',
        customerId: 'CUST017',
        cin: 'CIN017',
        applicationDate: '2024-10-12',
        mobile: '7890123456',
        email: 'oliverevans@example.com',
        statusCode: 'Inactive',
        accountType: 'Postpaid',
        currentTariffCode: 'R16',
        correctTariffCode: 'R16',
        tariffClass: 'LFN',
        feeder: 'Feeder17',
        feederId: 'FEED017',
        serviceCenter: 'Center17',
        distributionName: 'Distribution17',
        dssId: 'DSS017',
        ltPoleId: 'LT017',
        serviceWire: 'Wire17',
        upriser: 'Upriser17',
        region: 'Region17',
        businessHub: 'Hub17',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Retail',
        customerNIN: 'NIN017',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1200',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Mechanical',
        customerMeterManufacturer: 'Manufacturer17',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Oliver Evans',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-12'),
        status: 'Pending',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1018,
        customerFullName: 'Grace Wilson',
        accountNo: 'ACC018',
        meterNo: 'MTR018',
        address: '987 Cedar St',
        city: 'Coast City',
        lga: 'LGA18',
        state: 'State18',
        nearestLandmark: 'Near the cinema',
        latitude: '29.012345',
        longitude: '81.098765',
        customerId: 'CUST018',
        cin: 'CIN018',
        applicationDate: '2024-09-30',
        mobile: '8901234567',
        email: 'gracewilson@example.com',
        statusCode: 'Active',
        accountType: 'Prepaid',
        currentTariffCode: 'R17',
        correctTariffCode: 'R17',
        tariffClass: 'MD1',
        feeder: 'Feeder18',
        feederId: 'FEED018',
        serviceCenter: 'Center18',
        distributionName: 'Distribution18',
        dssId: 'DSS018',
        ltPoleId: 'LT018',
        serviceWire: 'Wire18',
        upriser: 'Upriser18',
        region: 'Region18',
        businessHub: 'Hub18',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Real Estate',
        customerNIN: 'NIN018',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '4200',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Prepaid - Smart',
        customerMeterManufacturer: 'Manufacturer18',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Grace Wilson',
        customerHasAccountNo: 'Yes',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'James Wilson',
        landlordPhone: '901-234-5678',
        tenantName: 'Lily Wilson',
        tenantPhone: '345-678-9012',
        meterCTRatio: '1:1',
        date: new Date('2024-09-10'),
        status: 'Approved',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1019,
        customerFullName: 'Henry Morgan',
        accountNo: 'ACC019',
        meterNo: 'MTR019',
        address: '654 Birch St',
        city: 'Star City',
        lga: 'LGA19',
        state: 'State19',
        nearestLandmark: 'Near the shopping mall',
        latitude: '30.123456',
        longitude: '80.987654',
        customerId: 'CUST019',
        cin: 'CIN019',
        applicationDate: '2024-10-11',
        mobile: '9012345678',
        email: 'henrymorgan@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R18',
        correctTariffCode: 'R18',
        tariffClass: 'LFN',
        feeder: 'Feeder19',
        feederId: 'FEED019',
        serviceCenter: 'Center19',
        distributionName: 'Distribution19',
        dssId: 'DSS019',
        ltPoleId: 'LT019',
        serviceWire: 'Wire19',
        upriser: 'Upriser19',
        region: 'Region19',
        businessHub: 'Hub19',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Hospitality',
        customerNIN: 'NIN019',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1800',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Analog',
        customerMeterManufacturer: 'Manufacturer19',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Henry Morgan',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-09'),
        status: 'Approved',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1020,
        customerFullName: 'Sophia Adams',
        accountNo: 'ACC020',
        meterNo: 'MTR020',
        address: '321 Walnut St',
        city: 'Smallville',
        lga: 'LGA20',
        state: 'State20',
        nearestLandmark: 'Near the market',
        latitude: '31.234567',
        longitude: '79.876543',
        customerId: 'CUST020',
        cin: 'CIN020',
        applicationDate: '2024-10-08',
        mobile: '0123456789',
        email: 'sophiaadams@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R19',
        correctTariffCode: 'R19',
        tariffClass: 'MD2',
        feeder: 'Feeder20',
        feederId: 'FEED020',
        serviceCenter: 'Center20',
        distributionName: 'Distribution20',
        dssId: 'DSS020',
        ltPoleId: 'LT020',
        serviceWire: 'Wire20',
        upriser: 'Upriser20',
        region: 'Region20',
        businessHub: 'Hub20',
        accountCategory: 'Commercial',
        connectionType: 'Un-Metered',
        custNatureOfBusiness: 'Construction',
        customerNIN: 'NIN020',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '5500',
        custHasMeter: 'No',
        customerMeterCategory: 'Prepaid - Smart',
        customerMeterManufacturer: 'Manufacturer20',
        customerMeterSaled: 'No',
        customerMeterAccessible: 'No',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Sophia Adams',
        customerHasAccountNo: 'No',
        customerGroup: 'Existing',
        isLandlord: 'Yes',
        landlordName: 'William Adams',
        landlordPhone: '234-567-8901',
        tenantName: 'Olivia Adams',
        tenantPhone: '678-901-2345',
        meterCTRatio: '1:1',
        date: new Date('2024-09-08'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1021,
        customerFullName: 'James Bailey',
        accountNo: 'ACC021',
        meterNo: 'MTR021',
        address: '456 Maple St',
        city: 'Metropolis',
        lga: 'LGA21',
        state: 'State21',
        nearestLandmark: 'Near the train station',
        latitude: '32.345678',
        longitude: '78.765432',
        customerId: 'CUST021',
        cin: 'CIN021',
        applicationDate: '2024-09-28',
        mobile: '1234567890',
        email: 'jamesbailey@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R20',
        correctTariffCode: 'R20',
        tariffClass: 'MD1',
        feeder: 'Feeder21',
        feederId: 'FEED021',
        serviceCenter: 'Center21',
        distributionName: 'Distribution21',
        dssId: 'DSS021',
        ltPoleId: 'LT021',
        serviceWire: 'Wire21',
        upriser: 'Upriser21',
        region: 'Region21',
        businessHub: 'Hub21',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Entertainment',
        customerNIN: 'NIN021',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1600',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Analog',
        customerMeterManufacturer: 'Manufacturer21',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'James Bailey',
        customerHasAccountNo: 'Yes',
        customerGroup: 'Existing',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-07'),
        status: 'Approved',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1022,
        customerFullName: 'Isabella Scott',
        accountNo: 'ACC022',
        meterNo: 'MTR022',
        address: '789 Elm St',
        city: 'Central City',
        lga: 'LGA22',
        state: 'State22',
        nearestLandmark: 'Near the library',
        latitude: '33.456789',
        longitude: '77.654321',
        customerId: 'CUST022',
        cin: 'CIN022',
        applicationDate: '2024-09-26',
        mobile: '2345678901',
        email: 'isabellascott@example.com',
        statusCode: 'Suspended',
        accountType: 'Prepaid',
        currentTariffCode: 'R21',
        correctTariffCode: 'R21',
        tariffClass: 'MD2',
        feeder: 'Feeder22',
        feederId: 'FEED022',
        serviceCenter: 'Center22',
        distributionName: 'Distribution22',
        dssId: 'DSS022',
        ltPoleId: 'LT022',
        serviceWire: 'Wire22',
        upriser: 'Upriser22',
        region: 'Region22',
        businessHub: 'Hub22',
        accountCategory: 'Residential',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Manufacturing',
        customerNIN: 'NIN022',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '3600',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Prepaid - Smart',
        customerMeterManufacturer: 'Manufacturer22',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Isabella Scott',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'Yes',
        landlordName: 'Michael Scott',
        landlordPhone: '345-678-9012',
        tenantName: 'Sophia Scott',
        tenantPhone: '567-890-1234',
        meterCTRatio: '1:1',
        date: new Date('2024-09-06'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1023,
        customerFullName: 'Lucas Miller',
        accountNo: 'ACC023',
        meterNo: 'MTR023',
        address: '321 Pine St',
        city: 'National City',
        lga: 'LGA23',
        state: 'State23',
        nearestLandmark: 'Near the university',
        latitude: '34.567890',
        longitude: '76.543210',
        customerId: 'CUST023',
        cin: 'CIN023',
        applicationDate: '2024-09-24',
        mobile: '3456789012',
        email: 'lucasmiller@example.com',
        statusCode: 'Active',
        accountType: 'Postpaid',
        currentTariffCode: 'R22',
        correctTariffCode: 'R22',
        tariffClass: 'LFN',
        feeder: 'Feeder23',
        feederId: 'FEED023',
        serviceCenter: 'Center23',
        distributionName: 'Distribution23',
        dssId: 'DSS023',
        ltPoleId: 'LT023',
        serviceWire: 'Wire23',
        upriser: 'Upriser23',
        region: 'Region23',
        businessHub: 'Hub23',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Automotive',
        customerNIN: 'NIN023',
        customerSupplyType: '1-Phase',
        customerEstimatedLoad: '1400',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Postpaid - Mechanical',
        customerMeterManufacturer: 'Manufacturer23',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Indoor',
        customerBillName: 'Lucas Miller',
        customerHasAccountNo: 'Yes',
        customerGroup: 'Existing',
        isLandlord: 'No',
        landlordName: '',
        landlordPhone: '',
        tenantName: '',
        tenantPhone: '',
        meterCTRatio: '1:1',
        date: new Date('2024-09-05'),
        status: 'Approved',
        supplyType: 'Single Phase',
        dateApproved: "2023-06-15",
      },
      {
        id: 1024,
        customerFullName: 'Emma Walker',
        accountNo: 'ACC024',
        meterNo: 'MTR024',
        address: '654 Poplar St',
        city: 'Opal City',
        lga: 'LGA24',
        state: 'State24',
        nearestLandmark: 'Near the fire station',
        latitude: '35.678901',
        longitude: '75.432109',
        customerId: 'CUST024',
        cin: 'CIN024',
        applicationDate: '2024-09-22',
        mobile: '4567890123',
        email: 'emmawalker@example.com',
        statusCode: 'Inactive',
        accountType: 'Prepaid',
        currentTariffCode: 'R23',
        correctTariffCode: 'R23',
        tariffClass: 'MD1',
        feeder: 'Feeder24',
        feederId: 'FEED024',
        serviceCenter: 'Center24',
        distributionName: 'Distribution24',
        dssId: 'DSS024',
        ltPoleId: 'LT024',
        serviceWire: 'Wire24',
        upriser: 'Upriser24',
        region: 'Region24',
        businessHub: 'Hub24',
        accountCategory: 'Commercial',
        connectionType: 'Metered',
        custNatureOfBusiness: 'Retail',
        customerNIN: 'NIN024',
        customerSupplyType: '3-Phase',
        customerEstimatedLoad: '3200',
        custHasMeter: 'Yes',
        customerMeterCategory: 'Prepaid - Smart',
        customerMeterManufacturer: 'Manufacturer24',
        customerMeterSaled: 'Yes',
        customerMeterAccessible: 'Yes',
        customerMeterLocation: 'Outdoor',
        customerBillName: 'Emma Walker',
        customerHasAccountNo: 'Yes',
        customerGroup: 'New',
        isLandlord: 'Yes',
        landlordName: 'Robert Walker',
        landlordPhone: '678-901-2345',
        tenantName: 'Ava Walker',
        tenantPhone: '890-123-4567',
        meterCTRatio: '1:1',
        date: new Date('2024-09-04'),
        status: 'Pending',
        supplyType: 'Three Phase',
        dateApproved: "2023-06-15",
      },
    ];
  }


  getCustomer(): Promise<Customer[]> {
    return Promise.resolve(this.getCustomers());
  }

  getNewCustomer(): Promise<Customer[]>{
    return Promise.resolve(this.getNewCustomer());
  }
  getCustomerById(id: number): Promise<Customer | null> {
    const customer = this.getCustomers().find(customer => customer.id === id) || null;
    return Promise.resolve(customer);
  }

  getNewCustomerById(id: number): Promise<Customer | null> {
    const customer = this.getNewCustomers().find(customer => customer.id === id) || null;
    return Promise.resolve(customer);
  }
  constructor() {}
}
