import { validateCustomer } from "../../model/customer";

export class CustomerMapper2 {
  static mapJsonToCustomers(data: any[][]): validateCustomer[] {
    return data.map(row => ({
      customer_full_name: row[0] || '',
      account_no: row[1] || '',
      meter_no: row[2] || '',
      address: row[3] || '',
      city: row[4] || '',
      lga: row[5] || '',
      state: row[6] || '',
      nearest_landmark: row[7] || '',
      setup_date: row[8] || null,
      latitude: row[9] || null,
      longitude: row[10] || null,
      customer_id: row[11] || '',
      cin: row[12] || '',
      application_date: row[13] || null,
      mobile: row[14] || '',
      email: row[15] || '',
      status_code: row[16] || '',
      account_type: row[17] || '',
      current_tariff_code: row[18] || '',
      correct_tariff_code: row[19] || '',
      tariff_class: row[20] || '',
      feeder: row[21] || '',
      feeder_id: row[22] || '',
      service_center: row[23] || '',
      distribution_name: row[24] || '',
      dss_id: row[25] || '',
      lt_pole_id: row[26] || '',
      service_wire: row[27] || '',
      upriser: row[28] || '',
      region: row[29] || '',
      business_hub: row[30] || '',
      account_category: row[31] || '',
      connection_type: row[32] || '',
      cust_nature_of_business: row[33] || '',
      customer_nin: row[34] || '',
      customer_supply_type: row[35] || '',
      customer_estimated_load: row[36] || '',
      cust_has_meter: row[37] || '',
      customer_meter_category: row[38] || '',
      customer_meter_manufacturer: row[39] || '',
      customer_meter_saled: row[40] || '',
      customer_meter_accessible: row[41] || '',
      customer_meter_location: row[42] || '',
      customer_bill_name: row[43] || '',
      customer_has_account_no: row[44] || '',
      customer_group: row[45] || '',
      is_landlord: row[46] || '',
      landlord_name: row[47] || '',
      landlord_phone: row[48] || '',
      tenant_name: row[49] || '',
      tenant_phone: row[50] || '',
      meter_ct_ratio: row[51] || '',
      
    }));
  }
}